/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fravemax.Vistas;



/**
 *
 * @author glk05
 */
public class Menu_Pincipal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Pincipal
     */
    public Menu_Pincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMproductos = new javax.swing.JMenuItem();
        jMagregar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMAgregarCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMCargarVenta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                escritorioAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1023, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        jMenu1.setText("| Articulo | ");
        jMenu1.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N

        jMproductos.setText("PRODUCTOS");
        jMproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMproductosMouseClicked(evt);
            }
        });
        jMproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMproductosActionPerformed(evt);
            }
        });
        jMenu1.add(jMproductos);

        jMagregar.setText("AGREGAR PRODUCTO");
        jMagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMagregarActionPerformed(evt);
            }
        });
        jMenu1.add(jMagregar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("| Cliente |");
        jMenu2.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N

        jMAgregarCliente.setText("Agregar Cliente");
        jMAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAgregarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jMAgregarCliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("| Venta |");
        jMenu3.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMCargarVenta.setText("CARGAR VENTA ");
        jMCargarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCargarVentaActionPerformed(evt);
            }
        });
        jMenu3.add(jMCargarVenta);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("| Salir |");
        jMenu4.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escritorioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_escritorioAncestorAdded
       
    }//GEN-LAST:event_escritorioAncestorAdded

    private void jMAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAgregarClienteActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ClienteVista bps = new ClienteVista();
        bps.setVisible(true);
        escritorio.add(bps);
        escritorio.moveToFront(bps);    }//GEN-LAST:event_jMAgregarClienteActionPerformed

    private void jMCargarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCargarVentaActionPerformed
         escritorio.removeAll();
        escritorio.repaint();
        Venta ded = new Venta();
        ded.setVisible(true);
        escritorio.add(ded);
        escritorio.moveToFront(ded);
    }//GEN-LAST:event_jMCargarVentaActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
    System.exit(0);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMproductosActionPerformed
     
         escritorio.removeAll();
        escritorio.repaint();
        Productos_Vista bps = new Productos_Vista();
        bps.setVisible(true);
        escritorio.add(bps);
        escritorio.moveToFront(bps);       
        
    }//GEN-LAST:event_jMproductosActionPerformed

    private void jMproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMproductosMouseClicked
        escritorio.removeAll();
        escritorio.repaint();
        Productos_Vista bps = new Productos_Vista();
        bps.setVisible(true);
        escritorio.add(bps);
        escritorio.moveToFront(bps);       
    }//GEN-LAST:event_jMproductosMouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
      
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMagregarActionPerformed
       escritorio.removeAll();
        escritorio.repaint();
        AgregarProducto pcta = new AgregarProducto();
        pcta.setVisible(true);
        escritorio.add(pcta);
        escritorio.moveToFront(pcta);
    }//GEN-LAST:event_jMagregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Pincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Pincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMAgregarCliente;
    private javax.swing.JMenuItem jMCargarVenta;
    private javax.swing.JMenuItem jMagregar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMproductos;
    // End of variables declaration//GEN-END:variables
}
